name: fresh_admin_web
publish_to: 'none'
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  go_router: ^14.2.0
  fl_chart: ^0.66.2
  shared:
    path: ../../shared

flutter:
  uses-material-design: true
  assets:
    - assets/logo_fresh.webp
